name: playeveryware/action-image-exists
description: Determine if an images exists on a container registry
inputs:
  token:
    description: 'Access token for the container registry'
    required: true
  organization:
    description: 'Name of the GitHub organization with the container registry'
    default: 'PlayEveryWare'
    required: true
  image-name:
    description: 'Name of the image to check'
    required: true
  image-tag:
    description: 'Tag of the image to check'
    required: true
outputs:
  exists:
    description: 'Boolean value of whether or not the image:tag exists on the registry'

runs:
  using: node16
  main: dist/index.js
